from pathlib import Path

from engine.agent.service import WorkspaceAgentError, WorkspaceAgentService
from engine.contracts.api import AgentStepStatus


def test_workspace_agent_blocks_scope_escape(tmp_path: Path) -> None:
    service = WorkspaceAgentService(
        workspace_root=str(tmp_path),
        max_steps=6,
        max_file_reads=4,
        max_context_chars=3000,
    )

    try:
        service.plan("Search /tmp and summarize the docs there.")
    except WorkspaceAgentError as exc:
        assert "outside the allowed workspace scope" in str(exc)
    else:  # pragma: no cover - safety guard
        raise AssertionError("Expected workspace scope escape to be blocked.")


def test_workspace_agent_reads_supported_files_and_builds_summary(tmp_path: Path) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "field-prep.md").write_text(
        "Field prep checklist\nPack batteries\nPack oral rehydration salts\n", encoding="utf-8"
    )
    (docs / "notes.txt").write_text(
        "Translator contact sheet and village visit sequence.\n", encoding="utf-8"
    )

    service = WorkspaceAgentService(
        workspace_root=str(tmp_path),
        max_steps=6,
        max_file_reads=4,
        max_context_chars=3000,
    )
    plan = service.plan("Search this workspace and summarize the field prep docs.")
    state = service.create_state(plan)

    completed_steps = [service.execute_step(plan, state, step) for step in plan.steps]

    assert all(step.status == AgentStepStatus.COMPLETED for step in completed_steps)
    assert state.summary_text is not None
    assert "field-prep.md" in state.summary_text
    assert "Pack batteries" in state.summary_text


def test_workspace_agent_plan_is_bounded_by_max_steps(tmp_path: Path) -> None:
    service = WorkspaceAgentService(
        workspace_root=str(tmp_path),
        max_steps=3,
        max_file_reads=4,
        max_context_chars=3000,
    )

    plan = service.plan("Prepare a briefing from the relevant workspace files.")

    assert len(plan.steps) == 3


def test_workspace_agent_generic_brief_tops_off_context_when_matches_are_sparse(
    tmp_path: Path,
) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "field-prep.md").write_text(
        "Pack oral rehydration salts and backup batteries.\n",
        encoding="utf-8",
    )
    (docs / "contacts.txt").write_text(
        "Translator contact sheet and village route details.\n",
        encoding="utf-8",
    )
    (tmp_path / "README-notes.md").write_text(
        "Morning briefing structure and sequencing notes.\n",
        encoding="utf-8",
    )

    service = WorkspaceAgentService(
        workspace_root=str(tmp_path),
        max_steps=6,
        max_file_reads=4,
        max_context_chars=4000,
    )
    plan = service.plan("Prepare a briefing from the relevant workspace files.")
    state = service.create_state(plan)

    for step in plan.steps:
        service.execute_step(plan, state, step)

    assert len(state.read_documents) >= 2
    assert state.summary_text is not None
    assert "field-prep.md" in state.summary_text
    assert "contacts.txt" in state.summary_text


def test_workspace_agent_architecture_brief_ignores_generated_noise_and_metadata(
    tmp_path: Path,
) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "offline-field-assistant-v1-technical-architecture.md").write_text(
        "Field Assistant architecture\n"
        "Local-first orchestration for grounded answers.\n"
        "One assistant surface with specialist routes underneath.\n",
        encoding="utf-8",
    )
    (docs / "offline-field-assistant-v1-product-spec.md").write_text(
        "Product spec\n"
        "Offline-first field workflows with approvals for durable actions.\n",
        encoding="utf-8",
    )
    (docs / "field-prep.md").write_text(
        "Field prep checklist\n"
        "Pack oral rehydration salts\n"
        "Pack backup batteries\n"
        "Confirm translator contact sheet before departure\n",
        encoding="utf-8",
    )
    (docs / "route-notes.md").write_text(
        "Route notes\n"
        "Bring printed maps for the first village visit.\n"
        "Meet the translator at first light.\n",
        encoding="utf-8",
    )

    output_dir = tmp_path / "output" / "playwright" / "live-qa"
    output_dir.mkdir(parents=True)
    (output_dir / "page.yml").write_text(
        "Field Assistant Chat\nDate: April 20, 2026\nStatus: Draft\nGenerated by Playwright\n",
        encoding="utf-8",
    )
    exports_dir = tmp_path / "data" / "exports"
    exports_dir.mkdir(parents=True)
    (exports_dir / "old-brief.md").write_text(
        "Generated workspace briefing\n"
        "Key points:\n"
        "- stale generated summary\n",
        encoding="utf-8",
    )

    egg_info = tmp_path / "field_assistant_engine.egg-info"
    egg_info.mkdir()
    (egg_info / "SOURCES.txt").write_text("generated metadata\n", encoding="utf-8")
    (tmp_path / "CONTRIBUTING.md").write_text(
        "Thanks for contributing.\nPlease open a pull request.\n",
        encoding="utf-8",
    )

    service = WorkspaceAgentService(
        workspace_root=str(tmp_path),
        max_steps=6,
        max_file_reads=4,
        max_context_chars=4000,
    )
    plan = service.plan(
        "Prepare a short workspace briefing about the current field assistant architecture."
    )
    state = service.create_state(plan)

    for step in plan.steps:
        service.execute_step(plan, state, step)

    reviewed = [document.relative_path for document in state.read_documents]
    assert len(reviewed) <= 4
    assert "docs/offline-field-assistant-v1-technical-architecture.md" in reviewed
    assert "docs/offline-field-assistant-v1-product-spec.md" in reviewed
    assert all(path != "CONTRIBUTING.md" for path in reviewed)
    assert all("output/" not in path for path in reviewed)
    assert all("data/exports/" not in path for path in reviewed)
    assert all(".egg-info" not in path for path in reviewed)
    assert state.summary_text is not None
    assert "Date:" not in state.summary_text
    assert "Status:" not in state.summary_text
    assert "Related docs:" not in state.summary_text
    assert "Related brief:" not in state.summary_text
    assert "Working title:" not in state.summary_text
    assert "Thanks for contributing" not in state.summary_text
    assert "Local-first orchestration for grounded answers" in state.summary_text
    assert "One assistant surface with specialist routes underneath" in state.summary_text
    assert "Pack oral rehydration salts" not in state.summary_text
    assert "Pack backup batteries" not in state.summary_text
    assert "Confirm translator contact sheet before departure" not in state.summary_text
