from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from engine.contracts.api import AgentRunStep, AgentStepStatus, new_id, utc_now

SUPPORTED_TEXT_EXTENSIONS = {
    ".c",
    ".cc",
    ".cfg",
    ".conf",
    ".cpp",
    ".css",
    ".csv",
    ".env",
    ".go",
    ".h",
    ".hpp",
    ".html",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".mjs",
    ".py",
    ".rb",
    ".rst",
    ".sh",
    ".sql",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".xml",
    ".yaml",
    ".yml",
}

SKIP_DIRECTORIES = {
    ".git",
    ".hg",
    ".playwright-cli",
    ".next",
    ".pytest_cache",
    ".ruff_cache",
    ".svn",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "exports",
    "node_modules",
    "output",
}

LOW_SIGNAL_FILE_NAMES = {
    "contributing.md",
    "sources.txt",
    "uv.lock",
}

LOW_SIGNAL_LINE_PREFIXES = (
    "author:",
    "created:",
    "date:",
    "goal:",
    "license:",
    "related brief:",
    "related docs:",
    "related local docs:",
    "mode:",
    "status:",
    "updated:",
    "version:",
    "working title:",
)

LOW_SIGNAL_LINE_SNIPPETS = (
    "thanks for contributing",
    "generated by",
)

SIGNAL_HINTS = (
    "agent",
    "architecture",
    "approval",
    "assistant",
    "contract",
    "desktop",
    "engine",
    "field",
    "local",
    "memory",
    "model",
    "offline",
    "orchestr",
    "policy",
    "retrieval",
    "route",
    "shell",
    "tool",
    "workspace",
)

VERB_HINTS = (
    "allows",
    "builds",
    "converts",
    "defines",
    "enforces",
    "handles",
    "keeps",
    "owns",
    "prepares",
    "provides",
    "routes",
    "ships",
    "supports",
    "uses",
)

ACTION_HINTS = (
    "bring",
    "check",
    "confirm",
    "draft",
    "gather",
    "keep",
    "load",
    "log",
    "meet",
    "pack",
    "prepare",
    "restock",
    "review",
    "save",
    "search",
    "summarize",
    "top",
    "translate",
)

ARCHITECTURE_TOKENS = {
    "agent",
    "architecture",
    "architectural",
    "assistant",
    "contract",
    "engine",
    "memory",
    "model",
    "offline",
    "orchestrator",
    "policy",
    "routing",
    "shell",
    "system",
}

ARCHITECTURE_PATH_HINTS = {
    "agent",
    "architecture",
    "architectural",
    "approval",
    "contract",
    "design",
    "engine",
    "model",
    "offline",
    "orchestr",
    "overview",
    "policy",
    "research",
    "routing",
    "shell",
    "spec",
    "system",
}

OPERATIONAL_PATH_HINTS = {
    "checklist",
    "contact",
    "contacts",
    "departure",
    "field-prep",
    "field_prep",
    "prep",
    "route",
    "routes",
    "visit",
    "visits",
}

OPERATIONAL_LINE_HINTS = {
    "backup batteries",
    "consent forms",
    "contact sheet",
    "departure",
    "oral rehydration salts",
    "pack ",
    "restock",
    "top up",
    "translator",
    "visit",
}

STOPWORDS = {
    "a",
    "about",
    "all",
    "and",
    "brief",
    "file",
    "files",
    "folder",
    "for",
    "from",
    "in",
    "of",
    "on",
    "prepare",
    "project",
    "relevant",
    "search",
    "summarize",
    "summary",
    "the",
    "this",
    "through",
    "workspace",
}


@dataclass(slots=True)
class WorkspaceAgentPlan:
    goal: str
    scope_root: str
    steps: list[AgentRunStep]
    output_tool_name: str | None = None


@dataclass(slots=True)
class WorkspaceCandidate:
    path: Path
    relative_path: str
    score: float
    size_bytes: int
    preview: str


@dataclass(slots=True)
class WorkspaceReadDocument:
    path: Path
    relative_path: str
    score: float
    excerpt: str


@dataclass(slots=True)
class WorkspaceAgentState:
    scope_root: Path
    top_entries: list[str] = field(default_factory=list)
    candidate_files: list[WorkspaceCandidate] = field(default_factory=list)
    read_documents: list[WorkspaceReadDocument] = field(default_factory=list)
    summary_text: str | None = None


class WorkspaceAgentError(ValueError):
    pass


class WorkspaceAgentService:
    def __init__(
        self,
        *,
        workspace_root: str,
        max_steps: int,
        max_file_reads: int,
        max_context_chars: int,
    ) -> None:
        self.workspace_root = Path(workspace_root).resolve()
        self.max_steps = max_steps
        self.max_file_reads = max_file_reads
        self.max_context_chars = max_context_chars

    def plan(self, goal: str) -> WorkspaceAgentPlan:
        scope_root = self._resolve_scope_root(goal)
        output_tool_name = self._select_output_tool(goal)
        steps = [
            self._step("inspect_scope", "Inspect workspace scope"),
            self._step("search_workspace", "Search workspace files"),
            self._step("read_candidates", "Read candidate documents"),
            self._step("synthesize_workspace", "Synthesize workspace findings"),
        ]
        if output_tool_name:
            steps.append(self._step("prepare_output", "Prepare durable output"))
        return WorkspaceAgentPlan(
            goal=goal,
            scope_root=str(scope_root),
            steps=steps[: self.max_steps],
            output_tool_name=output_tool_name,
        )

    def create_state(self, plan: WorkspaceAgentPlan) -> WorkspaceAgentState:
        return WorkspaceAgentState(scope_root=Path(plan.scope_root))

    def execute_step(
        self,
        plan: WorkspaceAgentPlan,
        state: WorkspaceAgentState,
        step: AgentRunStep,
    ) -> AgentRunStep:
        if step.kind == "inspect_scope":
            return self._inspect_scope(state, step)
        if step.kind == "search_workspace":
            return self._search_workspace(plan, state, step)
        if step.kind == "read_candidates":
            return self._read_candidates(state, step)
        if step.kind == "synthesize_workspace":
            return self._synthesize_workspace(plan, state, step)
        if step.kind == "prepare_output":
            return self._prepare_output(plan, state, step)
        return self._complete_step(step, "Skipped unknown workspace step.")

    def _inspect_scope(
        self,
        state: WorkspaceAgentState,
        step: AgentRunStep,
    ) -> AgentRunStep:
        entries = []
        for path in sorted(state.scope_root.iterdir(), key=lambda item: (item.is_file(), item.name.lower())):
            if path.name in SKIP_DIRECTORIES:
                continue
            entries.append(path.name + ("/" if path.is_dir() else ""))
            if len(entries) == 8:
                break
        state.top_entries = entries
        detail = (
            f"Scoped the workspace agent to `{state.scope_root}` and inspected the top-level entries."
        )
        return self._complete_step(step, detail, references=entries[:4])

    def _search_workspace(
        self,
        plan: WorkspaceAgentPlan,
        state: WorkspaceAgentState,
        step: AgentRunStep,
    ) -> AgentRunStep:
        tokens = self._search_tokens(plan.goal)
        architecture_focus = self._is_architecture_focused(tokens)
        candidate_limit = self._candidate_limit(tokens)
        candidates: list[WorkspaceCandidate] = []
        for path in self._iter_supported_files(state.scope_root):
            try:
                size_bytes = path.stat().st_size
            except OSError:
                continue
            preview = self._read_text(path, char_limit=1800)
            if preview is None:
                continue
            score = self._score_candidate(tokens, path, preview)
            if score <= 0:
                continue
            candidates.append(
                WorkspaceCandidate(
                    path=path,
                    relative_path=self._relative_path(path),
                    score=score,
                    size_bytes=size_bytes,
                    preview=preview,
                )
            )

        candidates.sort(
            key=lambda candidate: (-candidate.score, candidate.relative_path.lower())
        )
        strong_match_target = min(candidate_limit, 2)
        strong_candidates = [candidate for candidate in candidates if candidate.score >= 1.0]
        if architecture_focus and strong_candidates:
            focused_candidates = [
                candidate
                for candidate in strong_candidates
                if self._matches_architecture_focus(candidate)
            ]
            state.candidate_files = (
                focused_candidates or strong_candidates
            )[: max(candidate_limit, 1)]
            detail = (
                f"Found {len(state.candidate_files)} candidate files inside the workspace scope."
            )
            return self._complete_step(
                step,
                detail,
                references=[candidate.relative_path for candidate in state.candidate_files[:4]],
            )
        seen_paths = {candidate.path for candidate in candidates}
        if len(strong_candidates) < strong_match_target:
            for path in self._iter_supported_files(state.scope_root):
                if path in seen_paths:
                    continue
                preview = self._read_text(path, char_limit=600)
                if preview is None:
                    continue
                candidates.append(
                    WorkspaceCandidate(
                        path=path,
                        relative_path=self._relative_path(path),
                        score=0.01,
                        size_bytes=path.stat().st_size,
                        preview=preview,
                    )
                )
                seen_paths.add(path)
                if len(candidates) == candidate_limit:
                    break

        state.candidate_files = candidates[: max(candidate_limit, 1)]
        if not state.candidate_files:
            return self._blocked_step(
                step,
                "No supported text-like files were available inside the allowed workspace scope.",
            )

        detail = (
            f"Found {len(state.candidate_files)} candidate files inside the workspace scope."
        )
        return self._complete_step(
            step,
            detail,
            references=[candidate.relative_path for candidate in state.candidate_files[:4]],
        )

    def _read_candidates(
        self,
        state: WorkspaceAgentState,
        step: AgentRunStep,
    ) -> AgentRunStep:
        documents: list[WorkspaceReadDocument] = []
        for candidate in state.candidate_files[: self.max_file_reads]:
            excerpt = self._read_text(candidate.path, char_limit=2200)
            if not excerpt:
                continue
            documents.append(
                WorkspaceReadDocument(
                    path=candidate.path,
                    relative_path=candidate.relative_path,
                    score=candidate.score,
                    excerpt=excerpt,
                )
            )
        state.read_documents = documents
        if not documents:
            return self._failed_step(
                step,
                "Candidate files were found, but none of them could be read as supported text content.",
            )
        return self._complete_step(
            step,
            f"Read {len(documents)} workspace files and collected structured excerpts for synthesis.",
            references=[document.relative_path for document in documents[:4]],
        )

    def _synthesize_workspace(
        self,
        plan: WorkspaceAgentPlan,
        state: WorkspaceAgentState,
        step: AgentRunStep,
    ) -> AgentRunStep:
        summary = self._build_summary(plan, state)
        state.summary_text = summary
        references = [document.relative_path for document in state.read_documents[:4]]
        return self._complete_step(
            step,
            "Synthesized the workspace findings into bounded context for the assistant.",
            references=references,
        )

    def _prepare_output(
        self,
        plan: WorkspaceAgentPlan,
        state: WorkspaceAgentState,
        step: AgentRunStep,
    ) -> AgentRunStep:
        if not plan.output_tool_name:
            return self._failed_step(step, "No durable output type was selected for this goal.")
        if not state.summary_text:
            return self._failed_step(step, "Workspace findings were not ready for output planning.")
        return self._complete_step(
            step,
            f"Prepared `{plan.output_tool_name}` from the workspace findings and queued it for approval if needed.",
            references=[document.relative_path for document in state.read_documents[:3]],
        )

    def _build_summary(
        self,
        plan: WorkspaceAgentPlan,
        state: WorkspaceAgentState,
    ) -> str:
        scope_display = self._display_scope(Path(plan.scope_root))
        if not state.read_documents:
            summary = (
                "I reviewed the allowed workspace scope"
                + (f" in {scope_display}" if scope_display != "." else "")
                + ", but I did not find readable files that strongly matched the request."
            )
            if state.top_entries:
                summary += "\n\nVisible scope entries:\n- " + "\n- ".join(state.top_entries[:5])
            return summary[: self.max_context_chars - 1].rstrip() + "…" if len(summary) > self.max_context_chars else summary

        tokens = self._search_tokens(plan.goal)
        key_points = self._key_points_from_documents(state.read_documents, tokens=tokens)
        reviewed_files = [document.relative_path for document in state.read_documents[: self.max_file_reads]]
        sections = [
            self._overview_sentence(plan.goal, reviewed_files, scope_display),
        ]
        if key_points:
            sections.append("Key points:\n- " + "\n- ".join(key_points))
        sections.append("Files reviewed:\n- " + "\n- ".join(reviewed_files))

        summary = "\n\n".join(section.strip() for section in sections if section.strip()).strip()
        if len(summary) <= self.max_context_chars:
            return summary
        return summary[: self.max_context_chars - 1].rstrip() + "…"

    def _overview_sentence(
        self,
        goal: str,
        reviewed_files: list[str],
        scope_display: str,
    ) -> str:
        file_count = len(reviewed_files)
        goal_phrase = self._goal_phrase(goal)
        scope_phrase = (
            f" in {scope_display}"
            if scope_display not in {".", ""}
            else " in the workspace"
        )
        return (
            f"I reviewed {file_count} workspace file"
            f"{'' if file_count == 1 else 's'}{scope_phrase} and pulled together the "
            f"most relevant points for {goal_phrase}."
        )

    def _goal_phrase(self, goal: str) -> str:
        cleaned = re.sub(
            r"^(please\s+)?(search|find|summarize|prepare|create|write|draft|make|build|review)\s+",
            "",
            goal.strip(),
            flags=re.I,
        ).strip(" .")
        if not cleaned:
            return "the request"
        lowered = cleaned.lower()
        if lowered.startswith(("a ", "an ", "the ", "this ", "that ")):
            return cleaned
        return f"the request to {cleaned}"

    def _key_points_from_documents(
        self,
        documents: list[WorkspaceReadDocument],
        *,
        tokens: list[str],
    ) -> list[str]:
        points: list[str] = []
        seen: set[str] = set()
        for document in documents:
            for point in self._document_points(document, tokens=tokens):
                normalized = point.lower()
                if normalized in seen:
                    continue
                seen.add(normalized)
                points.append(point)
                if len(points) == 6:
                    return points
        return points

    def _document_points(
        self,
        document: WorkspaceReadDocument,
        *,
        tokens: list[str],
    ) -> list[str]:
        candidates: list[tuple[float, str]] = []
        seen: set[str] = set()
        architecture_focus = self._is_architecture_focused(tokens)

        for raw_line in document.excerpt.splitlines():
            line = self._clean_summary_line(raw_line)
            if not line:
                continue
            if self._is_low_signal_line(line):
                continue
            if self._is_link_only_line(raw_line, line):
                continue
            if self._should_skip_line_for_goal(
                line=line,
                relative_path=document.relative_path,
                tokens=tokens,
                architecture_focus=architecture_focus,
            ):
                continue
            score = self._point_signal_score(
                line,
                tokens=tokens,
                relative_path=document.relative_path,
            )
            if score <= 0:
                continue
            normalized = line.lower()
            if normalized in seen:
                continue
            seen.add(normalized)
            candidates.append((score, line))

        if not candidates:
            return []

        candidates.sort(key=lambda item: -item[0])
        return [line for _, line in candidates[:2]]

    def _clean_summary_line(self, line: str) -> str:
        cleaned = line.strip().strip("*").strip()
        cleaned = re.sub(r"^#{1,6}\s*", "", cleaned)
        cleaned = re.sub(r"^[\-\u2022]\s*", "", cleaned)
        cleaned = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", cleaned)
        cleaned = re.sub(r"\s+", " ", cleaned)
        return cleaned.rstrip(" .")

    def _is_low_signal_line(self, line: str) -> bool:
        lowered = line.lower()
        if any(lowered.startswith(prefix) for prefix in LOW_SIGNAL_LINE_PREFIXES):
            return True
        if any(snippet in lowered for snippet in LOW_SIGNAL_LINE_SNIPPETS):
            return True
        if lowered.endswith(":"):
            return True
        return False

    def _looks_like_heading(self, line: str) -> bool:
        if ":" in line:
            return False
        words = line.split()
        if len(words) > 6:
            return False
        return line == line.title() or line.isupper()

    def _is_link_only_line(self, raw_line: str, cleaned_line: str) -> bool:
        raw = raw_line.strip()
        return bool(
            re.match(r"^[-*+]\s+\[[^\]]+\]\([^)]+\)$", raw)
            or re.match(r"^\[[^\]]+\]\([^)]+\)$", raw)
            or re.match(r"^[A-Z][\w\s&/-]+(?:Architecture Brief|Product Spec|Research Synthesis)$", cleaned_line)
        )

    def _point_signal_score(
        self,
        line: str,
        *,
        tokens: list[str],
        relative_path: str,
    ) -> float:
        lowered = line.lower()
        words = lowered.split()
        if len(words) < 2:
            return -1.0

        score = 0.0
        architecture_focus = self._is_architecture_focused(tokens)
        if len(words) >= 7:
            score += 1.2
        elif len(words) >= 5:
            score += 0.6
        elif len(words) >= 2:
            score += 0.25

        if any(hint in lowered for hint in SIGNAL_HINTS):
            score += 1.6
        if any(hint in lowered for hint in VERB_HINTS):
            score += 1.0
        if words and words[0] in ACTION_HINTS:
            score += 0.8
        if any(token in lowered for token in {" is ", " are ", " should ", " can ", " will "}):
            score += 0.8
        score += self._goal_token_overlap_boost(lowered, tokens)
        if architecture_focus and any(hint in relative_path.lower() for hint in OPERATIONAL_PATH_HINTS):
            score -= 0.8
        if architecture_focus and any(hint in lowered for hint in OPERATIONAL_LINE_HINTS):
            score -= 2.0
        if architecture_focus and any(hint in lowered for hint in SIGNAL_HINTS):
            score += 1.1
        if self._looks_like_heading(line):
            score -= 1.4
        if (
            re.match(r"^(##?\s+)?[A-Z][A-Za-z0-9\s/-]{0,50}$", line)
            and len(words) <= 7
            and (not words or words[0] not in ACTION_HINTS)
            and not any(hint in lowered for hint in VERB_HINTS)
            and not any(token in lowered for token in {" is ", " are ", " should ", " can ", " will "})
        ):
            score -= 1.2
        if re.match(r"^[A-Za-z0-9 ._-]+$", line) and "/" not in line and len(words) <= 4:
            score -= 0.8

        return score

    def _should_skip_line_for_goal(
        self,
        *,
        line: str,
        relative_path: str,
        tokens: list[str],
        architecture_focus: bool,
    ) -> bool:
        lowered = line.lower()
        words = lowered.split()
        if not architecture_focus:
            return False
        if (
            (self._looks_like_heading(line) or (len(words) <= 4 and line == re.sub(r"[.]+$", "", line)))
            and not any(hint in lowered for hint in VERB_HINTS)
            and not any(token in lowered for token in {" is ", " are ", " should ", " can ", " will "})
        ):
            return True
        if self._goal_token_overlap_boost(lowered, tokens) > 0:
            return False
        if any(hint in lowered for hint in SIGNAL_HINTS):
            return False
        if any(hint in lowered for hint in VERB_HINTS):
            return False
        if any(hint in lowered for hint in OPERATIONAL_LINE_HINTS):
            return True
        return any(hint in relative_path.lower() for hint in OPERATIONAL_PATH_HINTS) and bool(
            re.match(r"^(pack|confirm|bring|top|restock|review|meet|check)\b", lowered)
        )

    def _goal_token_overlap_boost(self, lowered_line: str, tokens: list[str]) -> float:
        overlap_tokens = [
            token
            for token in tokens
            if token in lowered_line and token not in STOPWORDS and len(token) > 3
        ]
        return min(2.4, len(overlap_tokens) * 0.8)

    def _is_architecture_focused(self, tokens: list[str]) -> bool:
        return any(token in ARCHITECTURE_TOKENS for token in tokens)

    def _matches_architecture_focus(self, candidate: WorkspaceCandidate) -> bool:
        lowered_path = candidate.relative_path.lower()
        if any(hint in lowered_path for hint in ARCHITECTURE_PATH_HINTS):
            return True
        lowered_preview = candidate.preview.lower()
        return any(hint in lowered_preview for hint in ARCHITECTURE_PATH_HINTS)

    def _resolve_scope_root(self, goal: str) -> Path:
        requested = self._extract_scope_hint(goal)
        if not requested:
            return self.workspace_root

        requested_path = Path(requested).expanduser()
        if not requested_path.is_absolute():
            requested_path = (self.workspace_root / requested_path).resolve()
        else:
            requested_path = requested_path.resolve()

        try:
            requested_path.relative_to(self.workspace_root)
        except ValueError as exc:
            raise WorkspaceAgentError(
                f"Requested path `{requested}` is outside the allowed workspace scope."
            ) from exc

        if not requested_path.exists():
            raise WorkspaceAgentError(
                f"Requested scope `{requested}` does not exist inside the allowed workspace."
            )

        if requested_path.is_file() and not self._is_supported_text_file(requested_path):
            raise WorkspaceAgentError(
                f"Requested file `{requested}` is not a supported text-like workspace file."
            )

        return requested_path if requested_path.is_dir() else requested_path.parent

    def _extract_scope_hint(self, goal: str) -> str | None:
        quoted = re.findall(r"[\"']([^\"']+)[\"']", goal)
        for candidate in quoted:
            if "/" in candidate or candidate.startswith("."):
                return candidate

        path_match = re.search(
            r"(?:in|under|inside|from)\s+((?:\.\.?/|/)[^\s,;:]+|[A-Za-z0-9_.-]+/[A-Za-z0-9_./-]+)",
            goal,
            flags=re.I,
        )
        if path_match:
            return path_match.group(1)

        if re.search(r"(?:^|\s)(?:/|\.{1,2}/)", goal):
            token = re.search(r"((?:/|\.{1,2}/)[^\s,;:]+)", goal)
            if token:
                return token.group(1)

        return None

    def _search_tokens(self, goal: str) -> list[str]:
        tokens = re.findall(r"[a-z0-9]+", goal.lower())
        return [token for token in tokens if len(token) > 2 and token not in STOPWORDS]

    def _score_candidate(self, tokens: list[str], path: Path, preview: str) -> float:
        haystack = f"{path.as_posix()} {preview.lower()}"
        score = 0.0
        lowered_path = path.as_posix().lower()
        architecture_focus = self._is_architecture_focused(tokens)
        for token in tokens:
            if token in lowered_path:
                score += 2.0
            matches = haystack.count(token)
            if matches:
                score += min(3.0, matches * 0.35)
        score += self._path_priority_boost(tokens, lowered_path)
        score -= self._path_noise_penalty(lowered_path)
        if architecture_focus and any(hint in lowered_path for hint in OPERATIONAL_PATH_HINTS):
            score -= 2.4
        return score

    def _path_priority_boost(self, tokens: list[str], lowered_path: str) -> float:
        boost = 0.0
        file_name = Path(lowered_path).name

        if any(token in {"architecture", "architectural"} for token in tokens):
            if "architecture" in file_name:
                boost += 3.2
            if any(hint in lowered_path for hint in {"spec", "design", "research", "synthesis"}):
                boost += 1.8

        if any(token in {"brief", "briefing", "summary"} for token in tokens):
            if any(hint in lowered_path for hint in {"overview", "summary", "brief", "architecture", "spec"}):
                boost += 1.6

        if any(token in {"field", "assistant"} for token in tokens) and "field-assistant" in lowered_path:
            boost += 1.2

        if file_name == "readme.md":
            boost += 0.4

        return boost

    def _path_noise_penalty(self, lowered_path: str) -> float:
        penalty = 0.0
        file_name = Path(lowered_path).name
        if file_name in LOW_SIGNAL_FILE_NAMES:
            penalty += 2.0
        if any(fragment in lowered_path for fragment in {".egg-info", "/tests/", "/test-", "/tmp/"}):
            penalty += 1.8
        if any(fragment in lowered_path for fragment in {"/data/exports/", "/exports/"}):
            penalty += 3.2
        if lowered_path.endswith((".csv", ".json", ".yaml", ".yml")):
            penalty += 0.8
        return penalty

    def _candidate_limit(self, tokens: list[str]) -> int:
        if any(token in {"architecture", "architectural", "brief", "briefing", "overview", "spec"} for token in tokens):
            return min(self.max_file_reads, 4)
        return self.max_file_reads

    def _iter_supported_files(self, scope_root: Path):
        if scope_root.is_file():
            if self._is_supported_text_file(scope_root):
                yield scope_root
            return

        for path in scope_root.rglob("*"):
            if any(part in SKIP_DIRECTORIES or part.endswith(".egg-info") for part in path.parts):
                continue
            if not path.is_file():
                continue
            if self._is_supported_text_file(path):
                yield path

    def _is_supported_text_file(self, path: Path) -> bool:
        return path.suffix.lower() in SUPPORTED_TEXT_EXTENSIONS

    def _read_text(self, path: Path, *, char_limit: int) -> str | None:
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            return None
        text = text.replace("\r\n", "\n").replace("\r", "\n").strip()
        if not text:
            return None
        if "\x00" in text:
            return None
        if len(text) <= char_limit:
            return text
        return text[: char_limit - 1].rstrip() + "…"

    def _compact_excerpt(self, text: str) -> str:
        compact = re.sub(r"\n{3,}", "\n\n", text).strip()
        return compact

    def _relative_path(self, path: Path) -> str:
        try:
            return str(path.relative_to(self.workspace_root))
        except ValueError:
            return str(path)

    def _display_scope(self, scope_root: Path) -> str:
        try:
            relative = scope_root.relative_to(self.workspace_root)
            return "." if str(relative) == "." else str(relative)
        except ValueError:
            return str(scope_root)

    def _select_output_tool(self, goal: str) -> str | None:
        lowered = goal.lower()
        if "checklist" in lowered:
            return "create_checklist"
        if "task" in lowered or "todo" in lowered:
            return "create_task"
        if "report" in lowered and "export" not in lowered and "markdown" not in lowered:
            return "create_report"
        if (
            any(
                phrase in lowered
                for phrase in {
                    "export",
                    "markdown",
                    "save as markdown",
                    "save it as markdown",
                    "save as a document",
                    "save it as a document",
                    "export it",
                }
            )
            and "note" not in lowered
        ):
            return "export_brief"
        if any(keyword in lowered for keyword in {"message", "reply", "email"}) and any(
            verb in lowered for verb in {"prepare", "create", "write", "draft", "make", "build"}
        ):
            return "create_message_draft"
        if any(keyword in lowered for keyword in {"brief", "briefing", "note", "report"}) and any(
            verb in lowered for verb in {"prepare", "create", "write", "draft", "make", "build"}
        ):
            return "create_note"
        return None

    def _step(self, kind: str, title: str) -> AgentRunStep:
        now = utc_now()
        return AgentRunStep(
            id=new_id("step"),
            kind=kind,
            title=title,
            status=AgentStepStatus.PLANNED,
            created_at=now,
            updated_at=now,
        )

    def _complete_step(
        self,
        step: AgentRunStep,
        detail: str,
        *,
        references: list[str] | None = None,
    ) -> AgentRunStep:
        now = utc_now()
        return step.model_copy(
            update={
                "status": AgentStepStatus.COMPLETED,
                "detail": detail,
                "references": references or [],
                "updated_at": now,
            }
        )

    def _blocked_step(self, step: AgentRunStep, detail: str) -> AgentRunStep:
        return step.model_copy(
            update={
                "status": AgentStepStatus.BLOCKED,
                "detail": detail,
                "updated_at": utc_now(),
            }
        )

    def _failed_step(self, step: AgentRunStep, detail: str) -> AgentRunStep:
        return step.model_copy(
            update={
                "status": AgentStepStatus.FAILED,
                "detail": detail,
                "updated_at": utc_now(),
            }
        )
