#!/usr/bin/env bash
set -euo pipefail

export FIELD_ASSISTANT_ASSISTANT_BACKEND="${FIELD_ASSISTANT_ASSISTANT_BACKEND:-mlx}"
export FIELD_ASSISTANT_ASSISTANT_MODEL_NAME="${FIELD_ASSISTANT_ASSISTANT_MODEL_NAME:-gemma-4-e2b-it-4bit}"
export FIELD_ASSISTANT_ASSISTANT_MAX_TOKENS="${FIELD_ASSISTANT_ASSISTANT_MAX_TOKENS:-360}"
export FIELD_ASSISTANT_SPECIALIST_BACKEND="${FIELD_ASSISTANT_SPECIALIST_BACKEND:-ocr}"
export FIELD_ASSISTANT_EMBEDDING_BACKEND="${FIELD_ASSISTANT_EMBEDDING_BACKEND:-hash}"

uv run uvicorn engine.api.app:create_app --factory --host 127.0.0.1 --port "${FIELD_ASSISTANT_PORT:-8000}"
